package main

import (
	"fmt"
	"io"
	"math"
	"strconv"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/colespringer/waxbin"
	"github.com/colespringer/waxbin/model"
	"github.com/colespringer/waxbin/waxerr"
	"github.com/spf13/cobra"
)

func newDBThumbsCmd(g *globals) *cobra.Command {
	var olderThan, maxBytes string
	cmd := &cobra.Command{
		Use:   "thumbs",
		Short: "Report and prune the generated thumbnail cache",
		Long: "Reports what the generated thumbnail cache holds: the totals, the source " +
			"images it was derived from, and a breakdown per ladder rung. A requested size " +
			"rounds up to a rung, so one cover browsed at several sizes holds a derivative " +
			"per rung rather than per width asked for, and the breakdown is where that shows; " +
			"the totals alone report it as a single cached cover.\n\n" +
			"--older-than and --max-bytes prune rather than only report, and can be combined: " +
			"the age pass runs first, then the budget evicts until what is left fits. Both " +
			"order by when an entry was generated, because nothing records when one was last " +
			"served. A pruned thumbnail is regenerated by the next request that asks for it, " +
			"so a prune costs decode time rather than pictures. It frees pages inside the " +
			"catalog file; `waxbin db vacuum` returns that space to the filesystem.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			const op = "db thumbs"
			var policy waxbin.ThumbPrunePolicy
			pruning := olderThan != "" || maxBytes != ""
			if olderThan != "" {
				age, err := parseAge(op, olderThan)
				if err != nil {
					return err
				}
				policy.OlderThan = &age
			}
			if maxBytes != "" {
				budget, err := parseBytes(op, maxBytes)
				if err != nil {
					return err
				}
				policy.MaxBytes = &budget
			}

			lib, _, err := g.openLib(cmd, !pruning)
			if err != nil {
				return err
			}
			defer lib.Close()

			var removed int
			var freed int64
			if pruning {
				if removed, freed, err = lib.PruneThumbnails(ctx(cmd), policy); err != nil {
					return err
				}
			}
			rep, err := lib.ThumbCacheStats(ctx(cmd))
			if err != nil {
				return err
			}

			if g.jsonOut {
				return printJSON(cmd, toThumbCacheView(rep, pruning, removed, freed))
			}
			w := out(cmd)
			if pruning {
				fmt.Fprintf(w, "pruned %s, freed %s\n", plural(removed, "thumbnail"), byteLabel(freed))
				if removed > 0 {
					fmt.Fprintln(w, "run `waxbin db vacuum` to return the freed pages to the filesystem")
				}
				fmt.Fprintln(w)
			}
			printThumbReport(w, rep, time.Now())
			return nil
		},
	}
	cmd.Flags().StringVar(&olderThan, "older-than", "", "prune entries generated longer ago than this (30d, 36h, ...)")
	cmd.Flags().StringVar(&maxBytes, "max-bytes", "", "prune oldest first until the cache fits this budget (200MB, 512MiB, 0 empties it)")
	return cmd
}

// printThumbReport writes the cache census. now is passed in rather than read here so
// the age line is reproducible in a test.
func printThumbReport(w io.Writer, rep *model.ThumbCacheReport, now time.Time) {
	fmt.Fprintf(w, "thumbnails:    %s, %s across %s\n",
		plural(rep.Rows, "row"), byteLabel(rep.Bytes), plural(rep.Sources, "source image"))
	fmt.Fprintf(w, "source images: %s, %s\n", plural(rep.ArtSources, "row"), byteLabel(rep.ArtSourceBytes))
	// Both ends, because choosing a retention age needs the near end as much as the
	// far one: a newest entry from months back says the cache is dead weight, and one
	// from this morning says a client is still filling it. An empty cache has no range
	// at all, and printing the epoch for it would read as a cache sitting there since
	// 1970. UTC, not local, for the reason views.go gives: the stored value is a
	// resolved instant, and the reader's zone would shift the printed day.
	if rep.OldestAt > 0 {
		oldest, newest := time.Unix(0, rep.OldestAt).UTC(), time.Unix(0, rep.NewestAt).UTC()
		fmt.Fprintf(w, "generated:     %s to %s (oldest %s)\n",
			oldest.Format("2006-01-02"), newest.Format("2006-01-02"), agoLabel(now, oldest))
	}
	if len(rep.Rungs) == 0 {
		return
	}
	tw := tabwriter.NewWriter(w, 0, 2, 2, ' ', tabwriter.AlignRight)
	fmt.Fprintln(tw, "\n  SIZE\tROWS\tBYTES\t")
	for _, r := range rep.Rungs {
		fmt.Fprintf(tw, "  %d\t%d\t%s\t\n", r.Size, r.Rows, byteLabel(r.Bytes))
	}
	_ = tw.Flush()
}

// agoLabel renders how long before now a stamp was, at day granularity: the question
// a retention age answers is how many days back to cut, not how many minutes.
func agoLabel(now, then time.Time) string {
	days := int(now.Sub(then) / (24 * time.Hour))
	if days < 1 {
		// Not "today": the date beside this is a UTC calendar day, and a stamp from
		// after the reader's local midnight would make the two lines disagree.
		return "under a day ago"
	}
	return plural(days, "day") + " ago"
}

// byteUnits are the suffixes --max-bytes accepts. KB is 1000 and KiB is 1024, the
// usual split. Longest first, so KiB is matched before the bare B inside it.
var byteUnits = []struct {
	suffix string
	mult   int64
}{
	{"KIB", 1 << 10}, {"MIB", 1 << 20}, {"GIB", 1 << 30}, {"TIB", 1 << 40},
	{"KB", 1e3}, {"MB", 1e6}, {"GB", 1e9}, {"TB", 1e12},
	{"B", 1},
}

// parseBytes parses a byte budget: a plain count, or a count with one of byteUnits'
// suffixes. An unrecognized suffix is refused rather than ignored, since reading
// "200PB" as 200 bytes would empty a cache the operator meant to leave alone.
func parseBytes(op, s string) (int64, error) {
	bad := func() (int64, error) {
		return 0, waxerr.New(waxerr.CodeInvalid, op,
			"bad size "+s+" (use 200MB, 512MiB, or a plain byte count)")
	}
	digits := strings.ToUpper(strings.TrimSpace(s))
	mult := int64(1)
	for _, u := range byteUnits {
		if rest, ok := strings.CutSuffix(digits, u.suffix); ok {
			digits, mult = strings.TrimSpace(rest), u.mult
			break
		}
	}
	n, err := strconv.ParseInt(digits, 10, 64)
	if err != nil || n < 0 {
		return bad()
	}
	if n > math.MaxInt64/mult {
		return 0, waxerr.New(waxerr.CodeInvalid, op, "size out of range: "+s)
	}
	return n * mult, nil
}

// byteLabel renders a byte count for reading. These are budget-sized figures rather
// than exact accounting, and --json carries the exact count for anything that needs
// it. The scale is decimal, matching what --max-bytes reads from a KB/MB/GB suffix.
func byteLabel(n int64) string {
	const unit = 1000
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for v := n / unit; v >= unit; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGTPE"[exp])
}

// plural renders a count with its noun, taking the trivial "s" every noun here takes.
func plural(n int, noun string) string {
	if n == 1 {
		return fmt.Sprintf("%d %s", n, noun)
	}
	return fmt.Sprintf("%d %ss", n, noun)
}

type thumbRungView struct {
	Size  int   `json:"size"`
	Rows  int   `json:"rows"`
	Bytes int64 `json:"bytes"`
}

type thumbPrunedView struct {
	Rows  int   `json:"rows"`
	Bytes int64 `json:"bytes"`
}

type thumbCacheView struct {
	Rows           int              `json:"rows"`
	Bytes          int64            `json:"bytes"`
	Sources        int              `json:"sources"`
	ArtSources     int              `json:"artSources"`
	ArtSourceBytes int64            `json:"artSourceBytes"`
	OldestAt       int64            `json:"oldestAt,string,omitempty"` // unix ns; a string, see playStateView. 0 (empty cache) omitted
	NewestAt       int64            `json:"newestAt,string,omitempty"`
	Rungs          []thumbRungView  `json:"rungs"`
	Pruned         *thumbPrunedView `json:"pruned,omitempty"` // absent when no prune was asked for; present with zeroes when one matched nothing
}

func toThumbCacheView(rep *model.ThumbCacheReport, pruned bool, removed int, freed int64) thumbCacheView {
	v := thumbCacheView{
		Rows: rep.Rows, Bytes: rep.Bytes, Sources: rep.Sources,
		ArtSources: rep.ArtSources, ArtSourceBytes: rep.ArtSourceBytes,
		OldestAt: rep.OldestAt, NewestAt: rep.NewestAt,
		Rungs: make([]thumbRungView, 0, len(rep.Rungs)),
	}
	for _, r := range rep.Rungs {
		v.Rungs = append(v.Rungs, thumbRungView{Size: r.Size, Rows: r.Rows, Bytes: r.Bytes})
	}
	if pruned {
		v.Pruned = &thumbPrunedView{Rows: removed, Bytes: freed}
	}
	return v
}
