-- WaxBin schema v26: record which enrichment provider set a field's value.
--
-- field_provenance already records a field's source (tag|user|enrichment|organize),
-- its lock state, and, for a user edit, the curated value. What it cannot say is which
-- provider produced an enrichment value. The source is the flat literal "enrichment",
-- so a genre filled by MusicBrainz reads the same as one filled by ListenBrainz.
--
-- provider carries the stable provider id, such as "musicbrainz" or "lrclib", that set
-- the value. A consumer can then attribute a field to its source and work out a
-- metadata conflict. It is NULL for a tag or user edit, which have no external
-- provider, and for every pre-existing row.
--
-- The column lands here, ahead of the multi-provider enrichment work, so the field-edit
-- upsert can target the final row shape from the start. Later work only fills provider
-- in, and no second migration has to reshape a table the edit path already writes.
ALTER TABLE field_provenance ADD COLUMN provider TEXT;
